config/routes.rb
Rails.application.routes.draw do
  resources :comentarios
  resources :qualificacoes
  resources :clientes
  resources :restaurantes
end

app/models/cliente.rb
class Cliente < ApplicationRecord
    has_many :qualificacoes ,dependent: :destroy
    
    validates_presence_of :nome, message: " - deve ser preenchido"
    validates_uniqueness_of :nome, message: " - nome já cadastrado"
    validates_numericality_of :idade, greater_than: 0, less_than: 100, message: " - deve ser um número entre 0 e 100"
    
    def to_s
        nome
    end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

   def index
    @clientes = Cliente.all.page(params['page']).per(8)

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :idade)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_with(model: cliente, local: true) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
    <div class="form-group col-md-12">
    <%= form.label :nome %>
    <%= form.text_field :nome , class: "form-control"%>
  </div>
</div>


<div class="row">
    <div class="form-group col-md-12">    
    <%= form.label :idade %>
    <%= form.number_field :idade, class: "form-control" %>
  </div>
</div>

<div class="row">
    <div class="form-group col-md-6">
        <%= link_to 'Voltar', clientes_path, class: "btn btn-info" %>

        <%= form.submit :Criar, class: "btn btn-success pull-right"%>
  </div>
</div>
<% end %>

app/views/clientes/edit.html.erb
<div class="card-body">
    <h3>Editando Cliente</h3>
    <div class="border col-md-3">
            <br>
        <%= render 'form', cliente: @cliente %>
    </div>
</div>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Clientes</h3>
<%= link_to 'Novo', new_cliente_path, class: "btn btn-outline-success btn-sm pull-right" %>
<br>
<br>
<table class="table"> 
    <tr>
    <th>ID</th>
      <th>Nome</th>
      <th>Idade</th>
      <th class="text-center">Ação</th>
    </tr>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.id %></td>
        <td><%= cliente.nome %></td>
        <td><%= cliente.idade %></td>
        <td class="text-center">
        <%= link_to 'Vizualizar', cliente , class: "btn btn-outline-dark btn-sm"%>
        <%= link_to 'Editar', edit_cliente_path(cliente), class: "btn btn-outline-primary btn-sm" %>
        <%= link_to 'Deletar', cliente, method: :delete, data: { confirm: 'Você deseja excluir ?' }, class: "btn btn-outline-danger btn-sm" %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @clientes %>

app/views/clientes/new.html.erb
<div class="card-body">
    <h3>Novo Cliente</h3>
    <div class="border col-md-3">
        <%= render 'form', cliente: @cliente %>
    </div>
</div>

app/views/clientes/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<div class="card-body">
  <h4>Mostrando Cliente</h4>
  <div class="border col-md-3">
    <br>
    <div class="row">
      <div class="form-group col-md-10">
        <%= link_to "Nova qualificação", new_qualificacao_path,  class: "btn btn-primary pull-right" %>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-md-10">
        <strong>Nome:</strong>
        <input class="form-control" value="<%= @cliente.nome %>" disabled>
      </div>
    </div>


    <div class="row">
      <div class="form-group col-md-10">
        <strong>Idade</strong>
        <input class="form-control" value="<%= @cliente.idade %>" disabled>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-md-10">
        <%= link_to 'Voltar', clientes_path, class: "btn btn-info" %>
        <%= link_to 'Editar', edit_cliente_path(@cliente), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>