config/routes.rb
Rails.application.routes.draw do
  resources :comentarios
  resources :qualificacoes
  resources :clientes
  resources :restaurantes
end

app/models/restaurante.rb
class Restaurante < ApplicationRecord
    has_many :qualificacoes , dependent: :destroy
    has_and_belongs_to_many :pratos , dependent: :destroy
    has_many :comentarios, as: :comentavel , dependent: :destroy
    
    
    validate :primeira_letra_deve_ser_maiuscula
    validates_presence_of :nome, message: "deve ser preenchido"
    validates_presence_of :endereco, message: "deve ser preenchido"
    validates_presence_of :especialidade, message: "deve ser preenchido"
    validates_uniqueness_of :nome, message: "nome já cadastrado"
    validates_uniqueness_of :endereco, message: "endereço já cadastrado"

    has_attached_file :foto, :styles => { large: "600x600>",:medium => "300x300#", :thumb => "150x150>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :foto, :content_type => /\Aimage\/.*\Z/
    def to_s
        nome
    end
    
    private
        def primeira_letra_deve_ser_maiuscula
            errors.add(:nome,"primeira letra deve ser maiúscula") unless nome =~ /[A-Z].*/
        end

        
        
    
    
end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController

  def index
    @restaurantes = Restaurante.all.page(params['page']).per(8)
    @comentarios = Comentario.new
    respond_to do |format|
      format.html
      format.xml {render xml: @restaurantes}
      format.json {render json: @restaurantes}
    end
  end

  def new
    @restaurante = Restaurante.new
    @comentarios = Comentario.new
  end

  def create
    @restaurante = Restaurante.new(restaurante_params)
    if @restaurante.save
      redirect_to action: "show", id: @restaurante
    else
      render action: "new"
    end  
    @restaurante.save
  end

  def update
    @restaurante = Restaurante.find(params[:id])
    if @restaurante.update_attributes(restaurante_params)
      redirect_to action: "show", id: @restaurante
    else
      render action: "edit"
    end
  end

  def edit
    @restaurante = Restaurante.find(params[:id])
  end

  def show
    @restaurante = Restaurante.find(params[:id])
    @comentarios = Comentario.new

    respond_to do |format|
      format.html
      format.json {render json: @restaurante}
      format.xml {render xml: @restaurante}
    end
  end

  def destroy
    @restaurante = Restaurante.find(params[:id])
    @restaurante.destroy
    redirect_to(action: "index")
  end

  private


  def restaurante_params
    params.require(:restaurante).permit(:nome, :endereco, :especialidade, :foto)
  end


end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

app/views/restaurantes/_novo_comentario.html.erb
<%= form_for Comentario.new do |form| %>
<%= form.hidden_field :comentavel_id, value: @restaurante.id %>
<%= form.hidden_field :comentavel_type, value: @restaurante.class %>

<%= form.label :conteudo %> <br />
<%= form.text_area :conteudo%> 
<%= form.submit :Criar, class: "btn btn-success" %>
<% end %>

app/views/restaurantes/edit.html.erb
<%= form_for @restaurante do |form| %>

<div class="card-body">
<div class= "border col-md-6">

<div class="row">
    <div class="form-group col-md-10">
        <%= form.label :nome %>
        <%= form.text_field :nome , class: "form-control"%>
    </div>
</div>

<div class="row">
    <div class="form-group col-md-10">
         <%= form.label :endereco %>
         <%= form.text_field :endereco , class: "form-control"%>
    </div>
</div>

<div class="row">
    <div class="form-group col-md-10">
         <%= form.label :especialidade %>
         <%= form.text_field :especialidade , class: "form-control"%>
    </div>
</div>  

<div class="row">  
    <div class="form-group col-md-6">
        <%= form.file_field :foto %>
    </div>
</div>    

<div class="row">
    <div class="form-group col-md-6">
        <%= link_to 'Voltar', restaurantes_path, class: "btn btn-info" %>
        <%= form.submit :Criar, class: "btn btn-success pull-right"%>
    </div>
</div>

</div>
</div>

<% end %>

app/views/restaurantes/index.html.erb
<h3>Restaurantes</h3>
<%= link_to 'Novo', new_restaurante_path , class: "btn btn-outline-success btn-sm pull-right"%>
<br>
<br>
<table class="table"> 
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Endereço</th>
        <th>Especialidade</th>
        <th class="text-center">Ação</th>
    </tr>
    <% @restaurantes.each do |restaurante| %>
    <tr>
        <td> <%= restaurante.id  %> </td>
        <td> <%= restaurante.nome %> </td>
        <td> <%= restaurante.endereco %> </td>
        <td> <%= restaurante.especialidade %> </td>
        <td class="text-center">  
            <%= link_to 'Visualizar',restaurante, class: "btn btn-outline-dark btn-sm" %> 
            <%= link_to 'Editar', edit_restaurante_path(restaurante) , class: "btn btn-outline-primary btn-sm"%> 
            <%= link_to 'Deletar', restaurante, method: :delete, data: { confirm: 'Você deseja excluir ?' }, class: "btn btn-outline-danger btn-sm" %>
        </td>
      
    </tr>
    <% end %>
</table>
<%= paginate @restaurantes%>

app/views/restaurantes/new.html.erb
<%= form_for @restaurante , html: {multipart: true} do |form| %>

<ul>
    <% @restaurante.errors.full_messages.each do |msg| %>
    <li>
        <%= msg %>
    </li>
    <% end %>
</ul>

<div class="card-body">
    <h3>Novo Restaurante</h3>
    <div class="border col-md-5">
        <br>
        <div class="row">
            <div class="form-group col-md-12">
                <%= form.label :nome %>
                <%= form.text_field :nome , class: "form-control"%>
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-12">
                <%= form.label :endereco %>
                <%= form.text_field :endereco , class: "form-control"%>
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-12">
                <%= form.label :especialidade %>
                <%= form.text_field :especialidade , class: "form-control"%>
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-6">
                <%= form.file_field :foto %>
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-6">
                <%= link_to 'Voltar', restaurantes_path, class: "btn btn-info" %>
                <%= form.submit :Criar, class: "btn btn-success pull-right"%>
            </div>
        </div>

    </div>
</div>

<% end %>

app/views/restaurantes/show.html.erb
<div class="card-body">
    <h4>Mostrando Restaurante</h4>
    <div class="border col-md-6">
        <br>
        <div class="form-group col-md-6">
            <%= link_to "Qualificar este restaurante",new_qualificacao_path, class: "btn btn-primary"%>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                <strong>Nome</strong>
                <input class="form-control" value="<%= @restaurante.nome %>" disabled>

            </div>
            <div class="form-group col-md-6">
                <strong>Endereço: </strong>
                <input class="form-control" value="<%= @restaurante.endereco %>" disabled>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                <strong>Especialidade </strong>
                <input class="form-control" value="<%= @restaurante.especialidade %>" disabled>
            </div>

            <div class="form-group col-md-6">
                <strong>Nota média </strong>
                <input class="form-control" value=" <%= @restaurante.qualificacoes.average(:nota) %>" disabled>


            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                <strong>Qualificações </strong>
                <input class="form-control" value="<%= @restaurante.qualificacoes.count %>" disabled>

            </div>

            <div class="form-group col-md-6">
                <strong>Preço médio </strong>
                <input class="form-control" value=" <%= @restaurante.qualificacoes.average(:valor_gasto) %>" disabled>

            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                <%= comentarios @restaurante %>
            </div>
            <div class="form-group col-md-6">
                <%= novo_comentario @restaurante %>
            </div>

        </div>
        <div class="row">
            <div class="form-group col-md-5">
                <%= image_tag @restaurante.foto.url(:thumb) %>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6 float-right">
                <%= link_to 'Voltar', restaurantes_path, class: "btn btn-info" %>
                <%= link_to 'Editar', edit_restaurante_path(@restaurante) ,class: "btn btn-success pull-right" %>
            </div>
        </div>
    </div>
</div>