config/routes.rb
Rails.application.routes.draw do
  resources :comentarios
  resources :qualificacoes
  resources :clientes
  resources :restaurantes
end

app/models/comentario.rb
class Comentario < ApplicationRecord
    belongs_to :comentavel, polymorphic: true
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to restaurante_path, notice: 'Comentario was successfully created.' }
        format.js
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario = Comentario.find(params[:id])
    @comentario.destroy
    
    respond_to do |format|
      format.js { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:conteudo, :comentavel_id, :comentavel_type)
    end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_comentario.html.erb
<p id="comentario_<%= comentario.id %> ">
    <%= comentario.conteudo %> -
    <%= link_to '(remover)', comentario, method: :delete, remote: true,id: "remove_comentario_#{comentario.id}" %>
</p>

<% content_for :js do %>
    $('#remove_comentario_<%= comentario.id %> ').bind('ajax:success',function(){
        $('#comentario_<%= comentario.id%> ').remove();
        }
    );
<% end %>

app/views/comentarios/_comentarios.html.erb
<div id="comentarios">
    <h3>Comentários</h3>
    <% if comentarios.empty? %>
    Nenhum comentário
    <% else %>
    <%= render comentarios %>
    <% end %>
</div>

app/views/comentarios/_form.html.erb
<%= form_with(model: comentario, local: true) do |form| %>
  <% if comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :conteudo %>
    <%= form.text_area :conteudo %>
  </div>

  <div class="field">
    <%= form.label :comentavel_id %>
    <%= form.number_field :comentavel_id %>
  </div>

  <div class="field">
    <%= form.label :comentavel_type %>
    <%= form.text_field :comentavel_type %>
  </div>

  <div class="actions">
    <%= form.submit, class: 'btn btn-outline-danger' %>
  </div>
<% end %>

app/views/comentarios/_novo_comentario.html.erb
<%= form_for Comentario.new,remote: true do |form| %>
<%= form.hidden_field :comentavel_id, value: comentavel.id %>
<%= form.hidden_field :comentavel_type, value: comentavel.class %>
<div class="row">
    <div class="form-group col-md-9">
        <%= form.label :conteudo %> <br />
        <%= form.text_area :conteudo, class: "form-control" %>
    </div>

    <div class="form-group col-md-2 my-lg-5">
        <%= form.submit :Criar , class: "btn btn-outline-secondary "%>
    </div>
</div>
<% end %>

<% content_for :js do %>
    $('form').bind('ajax:complete', function(xhr, result){
        $('#comentarios').replaceWith(result.responseText);
        $('textarea').val("");
    });
<% end %>

app/views/comentarios/create.js.erb
<%= comentarios @comentario.comentavel %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Conteudo</th>
      <th>Comentavel</th>
      <th>Comentavel type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.conteudo %></td>
        <td><%= comentario.comentavel_id %></td>
        <td><%= comentario.comentavel_type %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Conteudo:</strong>
  <%= @comentario.conteudo %>
</p>

<p>
  <strong>Comentavel:</strong>
  <%= @comentario.comentavel_id %>
</p>

<p>
  <strong>Comentavel type:</strong>
  <%= @comentario.comentavel_type %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>