config/routes.rb
Rails.application.routes.draw do
  resources :comentarios
  resources :qualificacoes
  resources :clientes
  resources :restaurantes
end

app/views/layouts/_menu_principal.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light breadcrumb">
   
        <ul class="navbar-nav mr-auto ">

            <li class="nav-item pull-center">
                <%= link_to  "Clientes", clientes_path , class: "navbar-brand"%>
            </li>
            <br>
            <li class="nav-item">
                <%= link_to  "Qualificações", qualificacoes_path, class: "navbar-brand" %>
            </li>
            <br>
            <li class="nav-item">
                <%= link_to  "Restaurantes", restaurantes_path, class: "navbar-brand" %>
            </li>

        </ul>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>VotaPrato</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= yield :css %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.js"></script>
</head>

<body>
  <%= render  "layouts/menu_principal" %>

  <%= yield %>
  <script>
    <%= yield :js %>
  </script>
</body>

</html>

app/views/layouts/application.js.erb
<%= yield %>

<script>
<%= yield :js %>
</script>